import Head from "next/head";

import React from "react";

function Head() {
	return (
		<div>
			<Head>
				<title>Pagina name</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				{/* <link rel="icon" href="/favicon.ico" /> */}
			</Head>
		</div>
	);
}

export default Head;
