import Head from "next/head";

export default function Home() {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				<div className="container mx-auto">
					<div className="flex flex-wrap">
						<div className="w-full px-4">
							<h1 className="text-2xl text-gray-light">Index</h1>
						</div>
					</div>
				</div>
			</main>
		</div>
	);
}
